import { Buffer } from 'buffer';
import type { Document, Recipient, AuditTrail } from '@shared/schema';
import { db } from '../db';
import { documentImages } from '@shared/schema';
import { eq, and } from 'drizzle-orm';

interface CompletedDocumentData {
  document: Document;
  recipients: Recipient[];
  auditTrail: AuditTrail[];
  completedAt: Date;
}

export async function generateCompletedDocumentAttachment(data: CompletedDocumentData): Promise<{ filename: string; content: string; type: string }> {
  console.log('[PDF_GEN] 📄 Starting document attachment generation...');
  try {
    const { document } = data;
    console.log(`[PDF_GEN] Document: ${document.title} (ID: ${document.id})`);
    
    // For now, create a simple summary document since PDF generation is complex
    // In a production environment, you'd use a proper PDF library like PDFKit
    const summaryContent = createDocumentSummary(data);
    console.log(`[PDF_GEN] Summary content length: ${summaryContent.length} characters`);
    
    const attachment = {
      filename: `${document.title.replace(/[^a-zA-Z0-9]/g, '_')}_completed.txt`,
      content: Buffer.from(summaryContent).toString('base64'),
      type: 'text/plain'
    };
    
    console.log(`[PDF_GEN] ✅ Attachment generated: ${attachment.filename}`);
    return attachment;
  } catch (error: any) {
    console.error('[PDF_GEN] ❌ Error generating completed document attachment:', error);
    console.error('[PDF_GEN] Error details:', {
      message: error.message,
      stack: error.stack
    });
    throw new Error('Failed to generate completed document attachment');
  }
}

function createDocumentSummary(data: CompletedDocumentData): string {
  const { document, recipients, auditTrail, completedAt } = data;
  
  const summary = `
DOCUMENT COMPLETION SUMMARY
==========================

Document: ${document.title}
Completed: ${completedAt.toLocaleDateString()} at ${completedAt.toLocaleTimeString()}
Total Pages: ${document.pageCount}
Document ID: ${document.id}

RECIPIENTS & SIGNATURES
======================
${recipients.map((recipient, index) => `
${index + 1}. ${recipient.fullName} (${recipient.email})
   Role: ${recipient.role}
   Status: ${recipient.status}
   Signing Order: ${recipient.signingOrder}
`).join('')}

AUDIT TRAIL
===========
${auditTrail.map(entry => `
${entry.timestamp}: ${entry.action}
  Performed by: ${entry.performedBy}
  IP Address: ${entry.ipAddress}
  Details: ${entry.details ? JSON.stringify(entry.details) : 'N/A'}
`).join('')}

LEGAL NOTICE
============
This document has been electronically signed by all parties. Each signature 
has been captured with full audit trail including timestamps, IP addresses, 
and user agent information for legal compliance.

All signatures are legally binding and this document constitutes a complete
record of the signing process.

Certificate of Completion has been generated and appended to the original document.

Generated by Undersigned Platform
${new Date().toISOString()}
`;

  return summary.trim();
}